# Generated by Django 4.1.5 on 2023-06-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.CharField(max_length=256, verbose_name='作成者')),
                ('updated_by', models.CharField(max_length=256, verbose_name='更新者')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='タイトル')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('comment_type', models.IntegerField(choices=[(1, 'AIコメント'), (2, '質問コメント'), (3, '雑談コメント')], verbose_name='コメント種別')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント一覧',
            },
        ),
    ]
