# Generated by Django 4.1.5 on 2023-07-07 14:34

from django.db import migrations, models

from apps.question.models import Question


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_comment_commented_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.IntegerField(choices=Question.Category.choices, null=True, verbose_name='カテゴリー'),
        ),
    ]
