# Generated by Django 4.1.5 on 2023-06-22 14:03
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

import apps.user.models.user
from apps.user.models.user import generate_account_id


def maintenance_account_id(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    User モデルの account_id フィールドにユニークな値を登録する。

    Args:
        apps (Apps): Apps オブジェクト
        schema_editor (BaseDatabaseSchemaEditor): BaseDatabaseSchemaEditor オブジェクト
    """
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        user.account_id = generate_account_id()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(db_index=True, default=apps.user.models.user.generate_account_id, max_length=16, validators=[apps.user.models.user.account_id_validator], verbose_name='アカウントID'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/user-default.png', upload_to='profile_image/', verbose_name='プロフィール画像'),
        ),
        migrations.RunPython(
            maintenance_account_id,
        ),
    ]
