# Generated by Django 4.1.5 on 2023-06-22 15:52

import apps.user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_account_id_user_bio_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(db_index=True, default=apps.user.models.user.generate_account_id, max_length=16, validators=[apps.user.models.user.account_id_validator], unique=True, verbose_name='アカウントID'),
        ),
    ]
